// this file defines the codepages for keyboards

// keyboard codepage
#define KEY_A                    4
#define KEY_B                    5
#define KEY_C                    6
#define KEY_D                    7
#define KEY_E                    8
#define KEY_F                    9
#define KEY_G                    10
#define KEY_H                    11
#define KEY_I                    12
#define KEY_J                    13
#define KEY_K                    14
#define KEY_L                    15
#define KEY_M                    16
#define KEY_N                    17
#define KEY_O                    18
#define KEY_P                    19
#define KEY_Q                    20
#define KEY_R                    21
#define KEY_S                    22
#define KEY_T                    23
#define KEY_U                    24
#define KEY_V                    25
#define KEY_W                    26
#define KEY_X                    27
#define KEY_Y                    28
#define KEY_Z                    29
#define KEY_1                    30
#define KEY_2                    31
#define KEY_3                    32
#define KEY_4                    33
#define KEY_5                    34
#define KEY_6                    35
#define KEY_7                    36
#define KEY_8                    37
#define KEY_9                    38
#define KEY_0                    39
#define KEY_ENTER                40
#define KEY_ESC                  41
#define KEY_BACKSPACE            42
#define KEY_TAB                  43
#define KEY_SPACE                44
#define KEY_HYPHEN               45
#define KEY_EQUAL                46
#define KEY_LEFT_BRACE           47
#define KEY_RIGHT_BRACE          48
#define KEY_BACKSLASH            49
#define KEY_NUMBER               50
#define KEY_SEMICOLON            51
#define KEY_QUOTE                52
#define KEY_TILDE                53
#define KEY_COMMA                54
#define KEY_PERIOD               55
#define KEY_SLASH                56
#define KEY_CAPS_LOCK            57
#define KEY_F1                   58
#define KEY_F2                   59
#define KEY_F3                   60
#define KEY_F4                   61
#define KEY_F5                   62
#define KEY_F6                   63
#define KEY_F7                   64
#define KEY_F8                   65
#define KEY_F9                   66
#define KEY_F10                  67
#define KEY_F11                  68
#define KEY_F12                  69
#define KEY_PRINTSCREEN          70
#define KEY_SCROLL_LOCK          71
#define KEY_PAUSE                72
#define KEY_INSERT               73
#define KEY_HOME                 74
#define KEY_PAGE_UP              75
#define KEY_DELETE               76
#define KEY_END                  77
#define KEY_PAGE_DOWN            78
#define KEY_RIGHT                79
#define KEY_LEFT                 80
#define KEY_DOWN                 81
#define KEY_UP                   82
#define KEY_NUM_LOCK             83
#define KEYPAD_SLASH             84
#define KEYPAD_ASTERISK          85
#define KEYPAD_MINUS             86
#define KEYPAD_PLUS              87
#define KEYPAD_ENTER             88
#define KEYPAD_1                 89
#define KEYPAD_2                 90
#define KEYPAD_3                 91
#define KEYPAD_4                 92
#define KEYPAD_5                 93
#define KEYPAD_6                 94
#define KEYPAD_7                 95
#define KEYPAD_8                 96
#define KEYPAD_9                 97
#define KEYPAD_0                 98
#define KEYPAD_PERIOD            99
#define KEY_APP                  101
#define KEYPAD_EQUAL             103
#define KEY_F13                  104
#define KEY_F14                  105
#define KEY_F15                  106
#define KEY_F16                  107
#define KEY_F17                  108
#define KEY_F18                  109
#define KEY_F19                  110
#define KEY_F20                  111
#define KEY_F21                  112
#define KEY_F22                  113
#define KEY_F23                  114
#define KEY_F24                  115
#define KEY_EXEC                 116
#define KEY_HELP                 117
#define KEY_MENU                 118
#define KEY_SELECT               119
#define KEY_STOP                 120
#define KEY_AGAIN                121
#define KEY_UNDO                 122
#define KEY_CUT                  123
#define KEY_COPY                 124
#define KEY_PASTE                125
#define KEY_FIND                 126
#define KEY_MUTE                 127
#define KEY_VOL_UP               128
#define KEY_VOL_DOWN             129
#define LOCKING_CAPS             130
#define LOCKING_NUM              131
#define LOCKING_SCROLL           132
#define KEYPAD_COMMA             133
#define KEYPAD_EQUAL_SIGN        134
#define KEY_INT_1                135
#define KEY_INT_2                136
#define KEY_INT_3                137
#define KEY_INT_4                138
#define KEY_INT_5                139
#define KEY_INT_6                140
#define KEY_INT_7                141
#define KEY_INT_8                142
#define KEY_INT_9                143
#define KEY_LANG_1               144
#define KEY_LANG_2               145
#define KEY_LANG_3               146
#define KEY_LANG_4               147
#define KEY_LANG_5               148
#define KEY_LANG_6               149
#define KEY_LANG_7               150
#define KEY_LANG_8               151
#define KEY_LANG_9               152
#define KEY_ALTERNATE_ERASE      153
#define KEY_SYSREQ_ATTENTION     154
#define KEY_CANCEL               155
#define KEY_CLEAR                156
#define KEY_PRIOR                157
#define KEY_RETURN               158
#define KEY_SEPARATOR            159
#define KEY_OUT                  160
#define KEY_OPER                 161
#define KEY_CLEAR_AGAIN          162
#define KEY_CRSEL_PROPS          163
#define KEY_EXSEL                164
// A5 - AF RESERVED
#define KEYPAD_00                176 
#define KEYPAD_000               177 
#define THOUSANDS_SEPARATOR      178 
#define DECIMAL_SEPARATOR        179 
#define CURRENCY_UNIT            180 
#define CURRENCY_SUB_UNIT        181 
#define KEYPAD_LEFT_PARENTHESES  182 
#define KEYPAD_RIGHT_PARENTHESES 183 
#define KEYPAD_LEFT_BRACE        184 
#define KEYPAD_RIGHT_BRACE       185 
#define KEYPAD_TAB               186 
#define KEYPAD_BACKSPACE         187 
#define KEYPAD_A                 188 
#define KEYPAD_B                 189 
#define KEYPAD_C                 190 
#define KEYPAD_D                 191 
#define KEYPAD_E                 192 
#define KEYPAD_F                 193 
#define KEYPAD_XOR               194 
#define KEYPAD_CARET             195 
#define KEYPAD_PERCENT           196 
#define KEYPAD_LESS_THAN         197 
#define KEYPAD_GREATER_THAN      198 
#define KEYPAD_AMPERSAND         199 
#define KEYPAD_DOUBLE_AMPERSAND  200 
#define KEYPAD_PIPE              201 
#define KEYPAD_DOUBLE_PIPE       202 
#define KEYPAD_COLON             203 
#define KEYPAD_POUND             204 
#define KEYPAD_SPACE             205 
#define KEYPAD_AT                206 
#define KEYPAD_EXCLAMATION       207 
#define KEYPAD_MEMORY_STORE      208 
#define KEYPAD_MEMORY_RECALL     209 
#define KEYPAD_MEMORY_CLEAR      210 
#define KEYPAD_MEMORY_ADD        211 
#define KEYPAD_MEMORY_SUBTRACT   212 
#define KEYPAD_MEMORY_MULTIPLY   213 
#define KEYPAD_MEMORY_DIVIDE     214 
#define KEYPAD_PLUS_MINUS        215 
#define KEYPAD_CLEAR             216 
#define KEYPAD_CLEAR_ENTRY       217 
#define KEYPAD_BINARY            218 
#define KEYPAD_OCTAL             219 
#define KEYPAD_DECIMAL           220 
#define KEYPAD_HEXADECIMAL       221 
// DE - DF RESERVED
#define KEY_LEFT_CTRL            0xE0
#define KEY_LEFT_SHIFT           0xE1
#define KEY_LEFT_ALT             0xE2
#define KEY_LEFT_GUI             0xE3
#define KEY_RIGHT_CTRL           0xE4
#define KEY_RIGHT_SHIFT          0xE5
#define KEY_RIGHT_ALT            0xE6
#define KEY_RIGHT_GUI            0xE7

// consumer codepages
// Since many of these are application specific I've only included common values.
// There are many more controls than this, I may implement them in the future
// if I ever program some desktop applications for them. Consumer control values
// are 16-bit integers.

// transport controls
#define CON_PLAY                 0x00B0
#define CON_PAUSE                0x00B1
#define CON_RECORD               0x00B2
#define CON_FAST_FORWARD         0x00B3
#define CON_REWIND               0x00B4
#define CON_NEXT_TRACK           0x00B5
#define CON_PREV_TRACK           0x00B6
#define CON_STOP                 0x00B7
#define CON_EJECT                0x00B8
#define CON_RANDOM_PLAY          0x00B9
#define CON_REPEAT               0x00BC
#define CON_STOP_EJECT           0x00CC
#define CON_PLAY_PAUSE           0x00CD
#define CON_PLAY_SKIP            0x00CE

// volume controls
#define CON_VOLUME_UP            0x00E9
#define CON_VOLUME_DOWN          0x00EA
#define CON_MUTE                 0x00E2

// the below definitions are purely for convenience
#define KEY_CTRL   KEY_LEFT_CTRL
#define KEY_SHIFT  KEY_LEFT_SHIFT
#define KEY_ALT    KEY_LEFT_ALT
#define KEY_GUI    KEY_LEFT_GUI

#define L_CTRL     KEY_LEFT_CTRL
#define R_CTRL     KEY_RIGHT_CTRL

#define L_SHIFT    KEY_LEFT_SHIFT
#define R_SHIFT    KEY_RIGHT_SHIFT

#define L_ALT      KEY_LEFT_ALT
#define R_ALT      KEY_RIGHT_ALT

#define L_GUI      KEY_LEFT_GUI
#define R_GUI      KEY_RIGHT_GUI

#define PAGE_UP    KEY_PAGE_UP
#define PAGE_DOWN  KEY_PAGE_DOWN
#define PAGE_DN    KEY_PAGE_DOWN

#define L_BRACE    KEY_LEFT_BRACE
#define R_BRACE    KEY_RIGHT_BRACE

#define ENTER      KEY_ENTER
#define KEY_SEMI   KEY_SEMICOLON
#define SEMICOLON  KEY_SEMICOLON
#define PERIOD     KEY_PERIOD
#define COMMA      KEY_COMMA
#define BACKSPACE  KEY_BACKSPACE
#define BKSPACE    KEY_BACKSPACE
#define DELETE     KEY_DELETE
#define DEL        KEY_DELETE
#define BACKSLASH  KEY_BACKSLASH
#define BACKSLSH   KEY_BACKSLASH
#define BKSLASH    KEY_BACKSLASH
#define NUMLOCK    KEY_NUM_LOCK
#define CAPS       KEY_CAPS_LOCK
#define SCRLLCK    KEY_SCROLL_LOCK
#define PRTSCN     KEY_PRINTSCREEN
#define SLASH      KEY_SLASH
#define SPACE      KEY_SPACE
#define HYPHEN     KEY_HYPHEN
#define PAUSE      KEY_PAUSE
#define INSERT     KEY_INSERT
#define QUOTE      KEY_QUOTE
#define TILDE      KEY_TILDE
#define EQUAL      KEY_EQUAL
#define HOME       KEY_HOME
#define END        KEY_END

#define KP_AST     KEYPAD_ASTERISK
#define KP_MIN     KEYPAD_MINUS
#define KP_PLS     KEYPAD_PLUS
#define KP_ENT     KEYPAD_ENTER
#define KP_PRD     KEYPAD_PERIOD
#define KP_SLH     KEYPAD_SLASH
#define KP_EQL     KEYPAD_EQUAL
#define KP_COM     KEYPAD_COMMA
#define KP_00      KEYPAD_00
#define KP_000     KEYPAD_000

#define INS        KEY_INSERT
#define DEL        KEY_DELETE
#define LEFT       KEY_LEFT
#define RIGHT      KEY_RIGHT
#define DOWN       KEY_DOWN
#define UP         KEY_UP
